apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: grocery-tracker
  labels:
    app: web
    app.kubernetes.io/part-of: grocery-tracker
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
